-- POST
CREATE TABLE IF NOT EXISTS post
(
    id           BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id      BIGINT        NOT NULL,
    title        VARCHAR(100)  NOT NULL,
    content      VARCHAR(3000) NULL,
    status       VARCHAR(20)   NOT NULL,
    is_lightning TINYINT       NOT NULL DEFAULT 0,
    trip_id      BIGINT        NULL,
    hits         INT           NOT NULL DEFAULT 0,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- POST_FILE
CREATE TABLE IF NOT EXISTS post_file
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    post_id    BIGINT        NOT NULL,
    url        VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- POST TAG
CREATE TABLE IF NOT EXISTS post_tag
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(100) NOT NULL,
    post_id    BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
