name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APPLICATION: ${{ github.ref == 'refs/heads/prod' &&  secrets.PROD_APPLICATION || secrets.DEV_APPLICATION }}
      TEST_APPLICATION: ${{ secrets.TEST_APPLICATION }}

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: create applications.yml
        shell: bash
        run: |
          touch ./src/main/resources/application.yml
          echo "$APPLICATION" >> ./src/main/resources/application.yml
          touch ./src/test/resources/application.yml
          echo "$TEST_APPLICATION" >> ./src/test/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
