name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APPLICATION: ${{ github.ref == 'refs/heads/prod' &&  secrets.PROD_APPLICATION || secrets.DEV_APPLICATION }}
      TEST_APPLICATION: ${{ secrets.TEST_APPLICATION }}

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Set up Redis For Test
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-port: ${{ secrets.TEST_REDIS_PORT }}

      - name: Set up MySQL For Test
        uses: samin/mysql-action@v1.3
        with:
          mysql user: ${{ secrets.TEST_DB_USER }}
          mysql password: ${{ secrets.TEST_DB_PASSWORD }}
          mysql database: ${{ secrets.TEST_DB }}
          host port: ${{ secrets.TEST_DB_PORT }}

      - name: create applications.yml
        shell: bash
        run: |
          touch ./src/main/resources/application.yml
          echo "$APPLICATION" >> ./src/main/resources/application.yml
          mkdir -p ./src/test/resources/
          touch ./src/test/resources/application.yml
          echo "$TEST_APPLICATION" >> ./src/test/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
